apiVersion: v2
name: cluster-api-addon-provider
description: Helm chart for deploying the Cluster API addon provider.
type: application
# The version and appVersion are set by the CI script
version: 0.1.0
appVersion: "main"
