[project]
name = "capi_addons"
description = ""
readme = "README.md"
requires-python = ">=3.12"
license = "Apache-2.0"
license-files = ["LICENSE"]
version = "0.1.0"
dependencies = [
    "configomatic>=0.4.0",
    "easykube>=0.6.0",
    "jinja2>=3.1.6",
    "kopf>=1.44.6",
    "kube-custom-resource>=0.6.1",
    "pydantic>=2.13.5",
    "pyhelm3>=0.5.5",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "codespell>=2.4.3",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.6",
    "tox>=4.61.2",
    "tox-uv>=1.36.0",
]

[build-system]
requires = [
    "hatchling>=1.27"
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = [
    "/uv.lock",
]

[tool.black]
line-length = 88
target-version = ["py310"]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.ruff.format]
line-ending = "lf"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-builtins
    "A",
    # Ruff rules
    "RUF",
    # flake8-async
    "ASYNC",
    # pyupgrade
    "UP",
    # tidy imports
    "TID",
    # sorted imports
    "I",
    # check complexity
    "C90",
    # pep8 naming
    "N",
]
ignore = [
    "UP038", # deprecated
    "UP017", # remove and fix once 3.10 no longer tested in CI
]

[tool.mypy]
follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true

[tool.ruff.lint.mccabe]
# Flag errors (`C901`) whenever the complexity level exceeds 5.
max-complexity = 15
