apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cluster-api-addon-provider.fullname" . }}
  labels: {{ include "cluster-api-addon-provider.labels" . | nindent 4 }}
rules:
  # Manipulating CRDs (only allow patching of our own CRDs)
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - create
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    resourceNames:
      - helmreleases.addons.stackhpc.com
      - manifests.addons.stackhpc.com
    verbs:
      - update
      - patch
  # Required for kopf to watch resources properly
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  # Required for kopf to produce events properly
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  # We can manipulate our own objects
  - apiGroups:
      - addons.stackhpc.com
    resources:
      - "*"
    verbs:
      - "*"
  # We need to be able to read Cluster API clusters
  - apiGroups:
      - cluster.x-k8s.io
    resources:
      - clusters
    verbs:
      - list
      - watch
      - get
  # We need to be able to watch infrastructure clusters
  - apiGroups:
      - infrastructure.cluster.x-k8s.io
    resources:
      - "*"
    verbs:
      - list
      - watch
      - get
  # We need to be able to read configmaps and secrets
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - list
      - watch
      - get
