apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cluster-api-addon-provider.fullname" . }}
  labels: {{ include "cluster-api-addon-provider.labels" . | nindent 4 }}
spec:
  # Allow only one replica at once with the recreate strategy in order to avoid races
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: {{ include "cluster-api-addon-provider.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "cluster-api-addon-provider.selectorLabels" . | nindent 8 }}
      annotations:
        # Force the deployment to roll when the config changes
        addons.stackhpc.com/config-hash: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "cluster-api-addon-provider.fullname" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: etc-capi-addon-provider
              mountPath: /etc/capi-addon-provider
              readOnly: true
            - name: tmp
              mountPath: /tmp
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: etc-capi-addon-provider
          configMap:
            name: {{ include "cluster-api-addon-provider.fullname" . }}
        # Mount a writable directory at /tmp
        - name: tmp
          emptyDir: {}
