apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cluster-api-addon-provider.fullname" . }}
  # This role needs to apply to the Argo CD namespace
  namespace: {{ .Values.config | dig "argocd" "namespace" "argocd" }}
  labels: {{ include "cluster-api-addon-provider.labels" . | nindent 4 }}
subjects:
  # Target the service account in the release namespace
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "cluster-api-addon-provider.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cluster-api-addon-provider.fullname" . }}
