---
# Source: openstack-cluster/templates/secret-cloud-config.yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-cloud-credentials
stringData:
  # The Cluster API OpenStack provider requires project_id to be present,
  # even though it can be inferred from the application credential
  clouds.yaml: |
    clouds:
      openstack:
        auth:
          application_credential_id: <app cred id>
          application_credential_secret: <app cred secret>
          auth_url: <auth url>
          project_id: <project id>
        auth_type: v3applicationcredential
        identity_api_version: 3
        interface: public
        region_name: RegionOne
  cacert: |
    -----BEGIN CERTIFICATE-----
    ... certificate data ...
    -----END CERTIFICATE-----
